package transcoder

import (
	"context"

	transcoder "cloud.google.com/go/video/transcoder/apiv1"
	"cloud.google.com/go/video/transcoder/apiv1/transcoderpb"
	"github.com/simeon/castctl/internal/cli"
	"github.com/simeon/castctl/internal/client"
	"github.com/simeon/castctl/internal/output"
	"github.com/simeon/castctl/internal/parent"
	"github.com/spf13/cobra"
	"google.golang.org/api/iterator"
)

const jobsCollection = "jobs"

// NewJobCmd builds `castctl job ...`.
func NewJobCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:     "job",
		Short:   "Manage Transcoder batch jobs",
		Aliases: []string{"jobs"},
	}
	cmd.AddCommand(
		jobListCmd(),
		jobGetCmd(),
		jobCreateCmd(),
		jobDeleteCmd(),
	)
	return cmd
}

func withTranscoder(fn func(context.Context, *transcoder.Client) error) error {
	ctx := context.Background()
	c, err := client.Transcoder(ctx)
	if err != nil {
		return err
	}
	defer c.Close()
	return fn(ctx, c)
}

func jobColumns() []output.Column[*transcoderpb.Job] {
	return []output.Column[*transcoderpb.Job]{
		{Header: "id", Value: func(j *transcoderpb.Job) string { return parent.LastSegment(j.GetName()) }},
		{Header: "state", Value: func(j *transcoderpb.Job) string { return j.GetState().String() }},
		{Header: "created", Value: func(j *transcoderpb.Job) string { return ts(j.GetCreateTime()) }},
	}
}

func jobListCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "list",
		Short: "List jobs",
		RunE: func(_ *cobra.Command, _ []string) error {
			if err := cli.Current.RequireProjectLocation(); err != nil {
				return err
			}
			return withTranscoder(func(ctx context.Context, c *transcoder.Client) error {
				it := c.ListJobs(ctx, &transcoderpb.ListJobsRequest{
					Parent: parent.Location(cli.Current.Project, cli.Current.Location),
				})
				var items []*transcoderpb.Job
				for {
					j, err := it.Next()
					if err == iterator.Done {
						break
					}
					if err != nil {
						return err
					}
					items = append(items, j)
				}
				if cli.Current.JSON {
					return output.JSONProtoList(items)
				}
				if len(items) == 0 {
					return output.Empty("jobs", false)
				}
				return output.Table(items, jobColumns())
			})
		},
	}
}

func jobGetCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "get <id>",
		Short: "Get a job",
		Args:  cobra.ExactArgs(1),
		RunE: func(_ *cobra.Command, args []string) error {
			if err := cli.Current.RequireProjectLocation(); err != nil {
				return err
			}
			return withTranscoder(func(ctx context.Context, c *transcoder.Client) error {
				j, err := c.GetJob(ctx, &transcoderpb.GetJobRequest{
					Name: parent.Resource(cli.Current.Project, cli.Current.Location, jobsCollection, args[0]),
				})
				if err != nil {
					return err
				}
				return output.JSONProto(j)
			})
		},
	}
}

func jobCreateCmd() *cobra.Command {
	var file string
	c := &cobra.Command{
		Use:   "create",
		Short: "Create a job from -f spec.json (job ID is auto-generated by the API)",
		Args:  cobra.NoArgs,
		RunE: func(_ *cobra.Command, _ []string) error {
			if err := cli.Current.RequireProjectLocation(); err != nil {
				return err
			}
			job := &transcoderpb.Job{}
			if err := cli.UnmarshalSpec(file, job); err != nil {
				return err
			}
			return withTranscoder(func(ctx context.Context, c *transcoder.Client) error {
				// CreateJob is synchronous and returns the created Job.
				res, err := c.CreateJob(ctx, &transcoderpb.CreateJobRequest{
					Parent: parent.Location(cli.Current.Project, cli.Current.Location),
					Job:    job,
				})
				if err != nil {
					return err
				}
				return output.JSONProto(res)
			})
		},
	}
	c.Flags().StringVarP(&file, "file", "f", "", "path to job spec JSON (- for stdin)")
	_ = c.MarkFlagRequired("file")
	return c
}

func jobDeleteCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "delete <id>",
		Short: "Delete a job",
		Args:  cobra.ExactArgs(1),
		RunE: func(_ *cobra.Command, args []string) error {
			if err := cli.Current.RequireProjectLocation(); err != nil {
				return err
			}
			return withTranscoder(func(ctx context.Context, c *transcoder.Client) error {
				// DeleteJob is synchronous.
				if err := c.DeleteJob(ctx, &transcoderpb.DeleteJobRequest{
					Name: parent.Resource(cli.Current.Project, cli.Current.Location, jobsCollection, args[0]),
				}); err != nil {
					return err
				}
				cli.Infof("Deleted job %s", args[0])
				return nil
			})
		},
	}
}
